# 生成 100000 条熔炉配方 JSON
# 格式：{"input":"...","fuel":"...","output":"..."}

$itemNames = @'
coal_ore
deepslate_coal_ore
iron_ore
deepslate_iron_ore
gold_ore
deepslate_gold_ore
diamond_ore
deepslate_diamond_ore
emerald_ore
deepslate_emerald_ore
lapis_ore
deepslate_lapis_ore
redstone_ore
deepslate_redstone_ore
copper_ore
deepslate_copper_ore
nether_gold_ore
nether_quartz_ore
ancient_debris
raw_iron
raw_gold
raw_copper
iron_ingot
gold_ingot
copper_ingot
netherite_ingot
netherite_scrap
diamond
emerald
lapis_lazuli
redstone
quartz
amethyst_shard
iron_nugget
gold_nugget
stone
cobblestone
mossy_cobblestone
smooth_stone
stone_bricks
mossy_stone_bricks
cracked_stone_bricks
chiseled_stone_bricks
granite
polished_granite
diorite
polished_diorite
andesite
polished_andesite
calcite
tuff
dripstone_block
pointed_dripstone
dirt
coarse_dirt
rooted_dirt
podzol
mycelium
grass_block
sand
red_sand
sandstone
red_sandstone
smooth_sandstone
smooth_red_sandstone
chiseled_sandstone
chiseled_red_sandstone
cut_sandstone
cut_red_sandstone
gravel
flint
clay
clay_ball
glass
tinted_glass
obsidian
crying_obsidian
netherrack
nether_brick
nether_bricks
red_nether_bricks
blackstone
polished_blackstone
gilded_blackstone
polished_blackstone_bricks
basalt
smooth_basalt
magma_block
soul_sand
soul_soil
crimson_stem
warped_stem
crimson_planks
warped_planks
crimson_nylium
warped_nylium
nether_wart_block
warped_wart_block
shroomlight
end_stone
end_stone_bricks
purpur_block
purpur_pillar
end_rod
ice
packed_ice
blue_ice
snow_block
glowstone
glowstone_dust
prismarine
prismarine_bricks
dark_prismarine
sea_lantern
prismarine_shard
prismarine_crystals
nautilus_shell
heart_of_the_sea
oak_log
birch_log
spruce_log
jungle_log
acacia_log
dark_oak_log
mangrove_log
cherry_log
bamboo_block
oak_planks
birch_planks
spruce_planks
jungle_planks
acacia_planks
dark_oak_planks
mangrove_planks
cherry_planks
bamboo_planks
bamboo
stick
oak_leaves
birch_leaves
spruce_leaves
jungle_leaves
acacia_leaves
dark_oak_leaves
mangrove_leaves
cherry_leaves
azalea_leaves
flowering_azalea_leaves
oak_sapling
birch_sapling
spruce_sapling
jungle_sapling
acacia_sapling
dark_oak_sapling
cherry_sapling
mangrove_propagule
dandelion
poppy
blue_orchid
allium
azure_bluet
red_tulip
orange_tulip
white_tulip
pink_tulip
oxeye_daisy
cornflower
lily_of_the_valley
wither_rose
torchflower
sunflower
lilac
rose_bush
peony
pitcher_plant
fern
dead_bush
vine
lily_pad
kelp
dried_kelp
seagrass
sea_pickle
sugar_cane
cactus
hanging_roots
big_dripleaf
small_dripleaf
moss_block
moss_carpet
azalea
flowering_azalea
spore_blossom
glow_berries
torchflower_seeds
pitcher_pod
white_dye
orange_dye
magenta_dye
light_blue_dye
yellow_dye
lime_dye
pink_dye
gray_dye
light_gray_dye
cyan_dye
purple_dye
blue_dye
brown_dye
green_dye
red_dye
black_dye
white_wool
orange_wool
magenta_wool
light_blue_wool
yellow_wool
lime_wool
pink_wool
gray_wool
light_gray_wool
cyan_wool
purple_wool
blue_wool
brown_wool
green_wool
red_wool
black_wool
apple
golden_apple
enchanted_golden_apple
bread
cookie
pumpkin_pie
carrot
golden_carrot
potato
baked_potato
poisonous_potato
melon_slice
sweet_berries
wheat
wheat_seeds
beetroot
beetroot_seeds
pumpkin_seeds
melon_seeds
pumpkin
carved_pumpkin
jack_o_lantern
mushroom_stew
rabbit_stew
dried_kelp_block
cod
salmon
tropical_fish
pufferfish
cooked_cod
cooked_salmon
beef
cooked_beef
chicken
cooked_chicken
porkchop
cooked_porkchop
mutton
cooked_mutton
rabbit
cooked_rabbit
rotten_flesh
spider_eye
fermented_spider_eye
honey_bottle
honeycomb
honey_block
egg
brown_mushroom
red_mushroom
brown_mushroom_block
red_mushroom_block
mushroom_stem
nether_wart
sugar
bone
bone_block
bone_meal
string
cobweb
feather
leather
rabbit_hide
phantom_membrane
gunpowder
fire_charge
slime_ball
slime_block
magma_cream
ghast_tear
blaze_rod
blaze_powder
ender_pearl
eye_of_ender
ink_sac
glow_ink_sac
echo_shard
totem_of_undying
shulker_shell
trident
elytra
nether_star
dragon_egg
sculk
sculk_sensor
sculk_catalyst
sculk_shrieker
iron_block
gold_block
diamond_block
emerald_block
lapis_block
redstone_block
netherite_block
copper_block
exposed_copper
weathered_copper
oxidized_copper
raw_iron_block
raw_gold_block
raw_copper_block
coal_block
bone_block
quartz_block
chiseled_quartz_block
quartz_pillar
smooth_quartz
amethyst_block
budding_amethyst
wooden_sword
stone_sword
iron_sword
golden_sword
diamond_sword
netherite_sword
wooden_pickaxe
stone_pickaxe
iron_pickaxe
golden_pickaxe
diamond_pickaxe
netherite_pickaxe
wooden_axe
stone_axe
iron_axe
golden_axe
diamond_axe
netherite_axe
wooden_shovel
stone_shovel
iron_shovel
golden_shovel
diamond_shovel
netherite_shovel
wooden_hoe
stone_hoe
iron_hoe
golden_hoe
diamond_hoe
netherite_hoe
bow
crossbow
arrow
spectral_arrow
fishing_rod
carrot_on_a_stick
warped_fungus_on_a_stick
flint_and_steel
shears
lead
name_tag
saddle
compass
clock
spyglass
recovery_compass
map
book
writable_book
paper
bowl
bucket
water_bucket
lava_bucket
milk_bucket
powder_snow_bucket
leather_helmet
leather_chestplate
leather_leggings
leather_boots
chainmail_helmet
chainmail_chestplate
chainmail_leggings
chainmail_boots
iron_helmet
iron_chestplate
iron_leggings
iron_boots
golden_helmet
golden_chestplate
golden_leggings
golden_boots
diamond_helmet
diamond_chestplate
diamond_leggings
diamond_boots
netherite_helmet
netherite_chestplate
netherite_leggings
netherite_boots
turtle_helmet
iron_horse_armor
golden_horse_armor
diamond_horse_armor
leather_horse_armor
crafting_table
furnace
blast_furnace
smoker
campfire
soul_campfire
brewing_stand
cauldron
conduit
note_block
jukebox
tnt
end_crystal
chest
trapped_chest
barrel
ender_chest
shulker_box
anvil
chipped_anvil
damaged_anvil
hopper
dropper
dispenser
piston
sticky_piston
observer
comparator
repeater
iron_bars
glass_pane
ladder
scaffolding
torch
lantern
soul_lantern
tripwire_hook
rail
powered_rail
detector_rail
activator_rail
minecart
chest_minecart
hopper_minecart
tnt_minecart
oak_boat
spruce_boat
birch_boat
jungle_boat
acacia_boat
dark_oak_boat
mangrove_boat
cherry_boat
painting
item_frame
glow_item_frame
armor_stand
goat_horn
disc_fragment_5
music_disc_13
music_disc_cat
music_disc_blocks
music_disc_chirp
music_disc_far
music_disc_mall
music_disc_mellohi
music_disc_stal
music_disc_strad
music_disc_ward
music_disc_11
music_disc_wait
music_disc_otherside
music_disc_5
music_disc_pigstep
music_disc_relic
white_concrete_powder
orange_concrete_powder
magenta_concrete_powder
light_blue_concrete_powder
yellow_concrete_powder
lime_concrete_powder
pink_concrete_powder
gray_concrete_powder
light_gray_concrete_powder
cyan_concrete_powder
purple_concrete_powder
blue_concrete_powder
brown_concrete_powder
green_concrete_powder
red_concrete_powder
black_concrete_powder
white_concrete
orange_concrete
magenta_concrete
light_blue_concrete
yellow_concrete
lime_concrete
pink_concrete
gray_concrete
light_gray_concrete
cyan_concrete
purple_concrete
blue_concrete
brown_concrete
green_concrete
red_concrete
black_concrete
terracotta
white_terracotta
orange_terracotta
magenta_terracotta
light_blue_terracotta
yellow_terracotta
lime_terracotta
pink_terracotta
gray_terracotta
light_gray_terracotta
cyan_terracotta
purple_terracotta
blue_terracotta
brown_terracotta
green_terracotta
red_terracotta
black_terracotta
white_glazed_terracotta
orange_glazed_terracotta
magenta_glazed_terracotta
light_blue_glazed_terracotta
yellow_glazed_terracotta
lime_glazed_terracotta
pink_glazed_terracotta
gray_glazed_terracotta
light_gray_glazed_terracotta
cyan_glazed_terracotta
purple_glazed_terracotta
blue_glazed_terracotta
brown_glazed_terracotta
green_glazed_terracotta
red_glazed_terracotta
black_glazed_terracotta
white_stained_glass
orange_stained_glass
magenta_stained_glass
light_blue_stained_glass
yellow_stained_glass
lime_stained_glass
pink_stained_glass
gray_stained_glass
light_gray_stained_glass
cyan_stained_glass
purple_stained_glass
blue_stained_glass
brown_stained_glass
green_stained_glass
red_stained_glass
black_stained_glass
'@

$items = $itemNames -split "`r?`n" |
         Where-Object { $_.Trim() -ne "" } |
         ForEach-Object { "minecraft:" + $_.Trim() } |
         Select-Object -Unique

$n = $items.Count
Write-Host "物品总数: $n  最大可生成配方数: $($n * ($n - 1))"

$maxRecipes = 100000
$outputFile = "E:\mc\1.1.11mccreater\recipes.json"

$sw = [System.IO.StreamWriter]::new($outputFile, $false, [System.Text.Encoding]::UTF8)
$sw.WriteLine("[")

$count     = 0
$outputIdx = 0
$first     = $true
$done      = $false

for ($i = 0; $i -lt $n -and -not $done; $i++) {
    for ($j = 0; $j -lt $n -and -not $done; $j++) {
        if ($i -eq $j) { continue }

        $input  = $items[$i]
        $fuel   = $items[$j]
        $output = $items[$outputIdx % $n]
        $outputIdx++

        $line = '  {"input":"' + $input + '","fuel":"' + $fuel + '","output":"' + $output + '"}'

        if (-not $first) { $sw.WriteLine(",") }
        $sw.Write($line)
        $first = $false
        $count++

        if ($count -ge $maxRecipes) { $done = $true }
    }
}

$sw.WriteLine("")
$sw.WriteLine("]")
$sw.Flush()
$sw.Close()

$fileSize = (Get-Item $outputFile).Length / 1MB
Write-Host "完成！共生成 $count 条配方，文件大小: $([math]::Round($fileSize,2)) MB"
Write-Host "文件路径: $outputFile"
